import {defineConfig} from 'vitest/config';
import {playwright} from '@vitest/browser-playwright';
import {globSync} from 'tinyglobby';
import {viteStaticCopy} from 'vite-plugin-static-copy';
import totalBundlesize from '@blockquote/rollup-plugin-total-bundlesize';
// import {preventRewriteImportsTypeModule} from '@blockquote/vite-plugin-prevent-rewrite-imports-type-module';

const OUT_DIR = 'dev';
const ENTRIES_DIR = 'demo';
const ENTRIES_GLOB = [`${ENTRIES_DIR}/**/*.js`];
const ENTRY_EXCLUDE_GLOBS = [`${ENTRIES_DIR}/**/*.{test,spec}.js`];

const copyConfig = {
  targets: [
    {
      src: [`${ENTRIES_DIR}/**/*.*`, `!${ENTRIES_GLOB}`],
      dest: '.',
      rename: {stripBase: 1},
    },
  ],
};

// https://github.com/vitejs/vite/discussions/1736#discussioncomment-5126923
const entryFiles = [...new Set(globSync(ENTRIES_GLOB, {ignore: ENTRY_EXCLUDE_GLOBS}))].sort(
  (a, b) => a.localeCompare(b)
);

const entries = (() => {
  const map = new Map();

  for (const file of entryFiles) {
    const key = file.startsWith(`${ENTRIES_DIR}/`)
      ? file.slice(ENTRIES_DIR.length + 1).replace(/\.[^.]*$/, '')
      : file.replace(/\.[^.]*$/, '');

    if (map.has(key)) {
      throw new Error(
        `Duplicate demo entry key "${key}" generated by "${map.get(key)}" and "${file}".`
      );
    }

    map.set(key, file);
  }

  return Object.fromEntries(map);
})();

// https://vitejs.dev/config/
// https://vite-rollup-plugins.patak.dev/
// https://github.com/vitest-dev/vitest/commit/78b62ffe#diff-d3e264f3679867e205ed7eeb7622aa3b62bb0c4b1a4aa5a5983cb3aa118fcf3c

export default defineConfig(({command}) => ({
  test: {
    onConsoleLog(log, type) {
      if (type === 'stderr' && log.includes('in dev mode')) {
        return false;
      }
    },
    include: ['test/**/*.{test,spec}.?(c|m)[jt]s?(x)'],
    forceRerunTriggers: ['**/src/**/*.scss*'],
    browser: {
      enabled: true,
      headless: true,
      provider: playwright(),
      screenshotFailures: false,
      viewport: {width: 1920, height: 1080},
      instances: [
        {
          browser: 'chromium',
          provider: playwright({
            launchOptions: {
              args: [
                '--auto-open-devtools-for-tabs',
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-gpu',
              ],
            },
          }),
        },
      ],
    },
    coverage: {
      provider: 'istanbul',
      reportsDirectory: 'test/coverage/',
      reporter: ['lcov', 'json', 'text-summary'],
      enabled: true,
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      },
      include: ['**/src/**/*.{js,ts}'],
      exclude: ['**/src/**/index.*', '**/src/styles/'],
    },
  },
  plugins: command === 'build' ? [viteStaticCopy(copyConfig), totalBundlesize()] : [],
  optimizeDeps: {
    exclude: ['lit', 'lit-html'],
  },
  build: {
    outDir: OUT_DIR,
    rolldownOptions: {
      preserveEntrySignatures: 'exports-only',
      transform: {
        target: ['chrome71'],
      },
      input: entries,
      output: {
        dir: OUT_DIR,
        entryFileNames: '[name].js',
        format: 'es',
      },
      treeshake: true,
    },
  },
}));
