import {defineConfig} from 'vite';
import {nodeExternals} from 'rollup-plugin-node-externals';
import {globSync} from 'tinyglobby';

const ENTRIES_DIR = 'src';
const ENTRIES_GLOB = [`${ENTRIES_DIR}/**/*.{js,ts}`];
const ENTRY_EXCLUDE_GLOBS = [`${ENTRIES_DIR}/**/*.{test,spec}.{js,ts}`];

const entryFiles = [...new Set(globSync(ENTRIES_GLOB, {ignore: ENTRY_EXCLUDE_GLOBS}))].sort(
  (a, b) => a.localeCompare(b)
);

// https://github.com/vitejs/vite/discussions/1736#discussioncomment-5126923
const entries = (() => {
  const map = new Map();

  for (const file of entryFiles) {
    const key = file.startsWith(`${ENTRIES_DIR}/`)
      ? file.slice(ENTRIES_DIR.length + 1).replace(/\.[^.]*$/, '')
      : file.replace(/\.[^.]*$/, '');

    if (map.has(key)) {
      throw new Error(
        `Duplicate library entry key "${key}" generated by "${map.get(key)}" and "${file}".`
      );
    }

    map.set(key, file);
  }

  return Object.fromEntries(map);
})();

export default defineConfig({
  plugins: [nodeExternals()],
  build: {
    rolldownOptions: {
      transform: {
        target: ['es2022'],
        assumptions: {
          setPublicClassFields: true,
        },
        typescript: {
          removeClassFieldsWithoutInitializer: true,
        },
        decorator: {
          legacy: true,
        },
      },
      treeshake: true,
    },
    minify: false,
    lib: {
      entry: entries,
      formats: ['es'],
    },
  },
});
